$(eval $(call PackageDir,luci_luci-extra,luci/luci-extra))
$(eval $(call PackageDir,packages_shadowsocks-libev,packages/shadowsocks-libev))
$(eval $(call PackageDir,packages_webui-aria2,packages/webui-aria2))
$(eval $(call PackageDir,packages_yaaw,packages/yaaw))
$(eval $(call PackageDir,packages_dnscrypt-proxy,packages/dnscrypt-proxy))
$(eval $(call PackageDir,libs_libsodium,libs/libsodium))
